import pygame
ANCHO_VENTANA = 900
ALTO_VENTANA = 700
COLOR_NEGRO = (0,0,0)
MENSAJE_FIN_PROGRAMA = "Fin del programa"
TIEMPO_INTERVALO = 4
TIEMPO_MAXIMO = 7
MAXIMO_CARACTERES = 10
lista_texto_titulo = ["Escaleras", "y", "Serpientes"]

ESCRIBIENDO_NOMBRE = "clave_escribiendo_nombre"
VIENDO_MENU = "clave_viendo_menu"
VIENDO_SCORE = "clave_viendo_score"
VIENDO_FIN_JUEGO = "clave_viendo_fin_juego"
USUARIO_MOVIDO = "clave_usuario_movido"
INICIO_CRONOMETRO = "clave_inicio_cronometro"
CORRER_JUEGO = "clave_correr_juego"
JUGANDO = "clave_jugando"
JUEGO_TERMINADO = "clave_juego_terminado"
ELIGIO_OPCION_PREGUNTA = "clave_eligio_opcion_pregunta"
OPCION_JUGAR = "clave_rect_opcion_jugar"
OPCION_SCORE = "clave_rect_opcion_score"
OPCION_SALIR = "clave_rect_opcion_salir"
OPCION_A = "rect_opcion_a"
OPCION_B = "rect_opcion_b"
OPCION_C = "rect_opcion_c"
OPCION_FIN_JUEGO = "rect_opcion_fin_juego"
OPCION_MENU = "rect_opcion_menu"
OPCION_VOLVER_MENU = "clave_rect_opcion_volver_menu"
IMAGEN = "clave_imagen"
UBICACION = "clave_ubicacion"
MENSAJE_INFORMAR_CASILLERO = "Quedaste en el casillero: "
MENSAJE_FIN_PROGRAMA = "Fin del programa"