import pygame
fondo_inicio_pantalla = pygame.image.load("Imagenes/fondo_inicio_pantalla.png")
portada = pygame.image.load("Imagenes/portada titulo.png")

casillero_azul = pygame.image.load("Imagenes/casillero azul.png")
casillero_rojo = pygame.image.load("Imagenes/casillero rojo.png")
casillero_amarillo = pygame.image.load("Imagenes/casillero amarillo.png")
casillero_verde = pygame.image.load("Imagenes/casillero verde.png")
casillero_blanco = pygame.image.load("Imagenes/casillero blanco.png")
imagen_marco_peticion = pygame.image.load("Imagenes/marco rectangulo.png")
imagen_marco_pregunta = pygame.image.load("Imagenes/marco rectangulo.png")
imagen_rectangulo_negro = pygame.image.load("Imagenes/rectangulo negro.png")
imagen_casillero_negro = pygame.image.load("Imagenes/casillero negro.png")
imagen_fondo = pygame.image.load("Imagenes/rectangulo amarillo.png")
imagen_rectangulo_verde = pygame.image.load("Imagenes/rectangulo verde.png")
imagen_rectangulo_rojo = pygame.image.load("Imagenes/rectangulo rojo.png")
imagen_rectangulo_amarillo = pygame.image.load("Imagenes/rectangulo amarillo.png")
portada = pygame.image.load("Imagenes/portada titulo.png")

imagen_rectangulo_negro = pygame.transform.scale(imagen_casillero_negro,(220,40))
imagen_fondo_fin_juego = pygame.transform.scale(casillero_blanco,(600,400))
imagen_fondo_volver_menu = pygame.transform.scale(casillero_blanco,(65,30))
imagen_marco_pregunta = pygame.transform.scale(imagen_marco_pregunta,(900,100))
imagen_rectangulo_amarillo = pygame.transform.scale(imagen_rectangulo_amarillo,(220,90))
imagen_rectangulo_verde = pygame.transform.scale(imagen_rectangulo_verde,(220,90))
imagen_rectangulo_rojo = pygame.transform.scale(imagen_rectangulo_rojo,(220,90))
imagen_fondo = pygame.transform.scale(imagen_fondo,(220,90))
imagen_marco_peticion = pygame.transform.scale(imagen_marco_peticion,(400,100))