import pygame
icono = pygame.image.load("Imagenes/icono_juego.png")
casillero_azul = pygame.image.load("Imagenes/casillero azul.png")
casillero_rojo = pygame.image.load("Imagenes/casillero rojo.png")
casillero_blanco = pygame.image.load("Imagenes/casillero blanco.png")
casillero_negro = pygame.image.load("Imagenes/casillero negro.png")
casillero_amarillo = pygame.image.load("Imagenes/casillero amarillo.png")
casillero_verde = pygame.image.load("Imagenes/casillero verde.png")
imagen_fondo_titulo = pygame.image.load("Imagenes/Imagen_Titulo.png")

imagen_rectangulo_amarillo = pygame.image.load("Imagenes/rectangulo amarillo.png")
imagen_rectangulo_verde = pygame.image.load("Imagenes/rectangulo verde.png")
imagen_rectangulo_rojo = pygame.image.load("Imagenes/rectangulo rojo.png")
fondo_inicio_pantalla = pygame.image.load("Imagenes/fondo_inicio_pantalla.png")
imagen_marco_pregunta = pygame.image.load("Imagenes/marco rectangulo.png")
imagen_casillero_negro = pygame.image.load("Imagenes/casillero negro.png")
portada = pygame.image.load("Imagenes/portada titulo.png")

imagen_marco_pregunta = pygame.transform.scale(imagen_marco_pregunta,(900,100))
imagen_rectangulo_verde = pygame.transform.scale(imagen_rectangulo_verde,(220,90))
imagen_rectangulo_rojo = pygame.transform.scale(imagen_rectangulo_rojo,(220,90))
imagen_rectangulo_amarillo = pygame.transform.scale(imagen_rectangulo_amarillo,(220,90))
casillero_blanco = pygame.transform.scale(casillero_blanco,(600,400))